# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'activity.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 678)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-30, 0, 851, 651))
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard_1 = QtWidgets.QWidget()
        self.dashboard_1.setObjectName("dashboard_1")
        self.btToGetStarted = QtWidgets.QPushButton(self.dashboard_1)
        self.btToGetStarted.setGeometry(QtCore.QRect(170, 250, 151, 151))
        self.btToGetStarted.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btToGetStarted.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btToGetStarted.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btToGetStarted.setIconSize(QtCore.QSize(50, 50))
        self.btToGetStarted.setFlat(False)
        self.btToGetStarted.setObjectName("btToGetStarted")
        self.label_2 = QtWidgets.QLabel(self.dashboard_1)
        self.label_2.setGeometry(QtCore.QRect(330, 310, 51, 31))
        self.label_2.setStyleSheet(
            "QLabel {\n" "    font-size: 30px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_2.setObjectName("label_2")
        self.btRunning = QtWidgets.QPushButton(self.dashboard_1)
        self.btRunning.setGeometry(QtCore.QRect(390, 250, 151, 151))
        self.btRunning.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btRunning.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunning.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunning.setIconSize(QtCore.QSize(50, 50))
        self.btRunning.setFlat(False)
        self.btRunning.setObjectName("btRunning")
        self.frame = QtWidgets.QFrame(self.dashboard_1)
        self.frame.setGeometry(QtCore.QRect(20, 0, 831, 111))
        self.frame.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 40, 431, 31))
        self.label.setStyleSheet(
            "QLabel {\n" "    font-size: 30px;\n" "    font-weight: bold;\n" "}"
        )
        self.label.setObjectName("label")
        self.btRunning_2 = QtWidgets.QPushButton(self.frame)
        self.btRunning_2.setGeometry(QtCore.QRect(670, 30, 111, 61))
        self.btRunning_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btRunning_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunning_2.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunning_2.setIconSize(QtCore.QSize(50, 50))
        self.btRunning_2.setFlat(False)
        self.btRunning_2.setObjectName("btRunning_2")
        self.btRunning_3 = QtWidgets.QPushButton(self.frame)
        self.btRunning_3.setGeometry(QtCore.QRect(540, 30, 111, 61))
        self.btRunning_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btRunning_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunning_3.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunning_3.setIconSize(QtCore.QSize(50, 50))
        self.btRunning_3.setFlat(False)
        self.btRunning_3.setObjectName("btRunning_3")
        self.btRunning_5 = QtWidgets.QPushButton(self.dashboard_1)
        self.btRunning_5.setGeometry(QtCore.QRect(600, 250, 151, 151))
        self.btRunning_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btRunning_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunning_5.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunning_5.setIconSize(QtCore.QSize(50, 50))
        self.btRunning_5.setFlat(False)
        self.btRunning_5.setObjectName("btRunning_5")
        self.label_11 = QtWidgets.QLabel(self.dashboard_1)
        self.label_11.setGeometry(QtCore.QRect(550, 310, 51, 31))
        self.label_11.setStyleSheet(
            "QLabel {\n" "    font-size: 30px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_11.setObjectName("label_11")
        self.stackedWidget.addWidget(self.dashboard_1)
        self.createProject_2 = QtWidgets.QWidget()
        self.createProject_2.setObjectName("createProject_2")
        self.frame_14 = QtWidgets.QFrame(self.createProject_2)
        self.frame_14.setGeometry(QtCore.QRect(30, 0, 821, 111))
        self.frame_14.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_50 = QtWidgets.QLabel(self.frame_14)
        self.label_50.setGeometry(QtCore.QRect(20, 40, 211, 31))
        self.label_50.setStyleSheet(
            "QLabel {\n" "    font-size: 30px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_50.setObjectName("label_50")
        self.txtCreateProjectNama = QtWidgets.QLineEdit(self.createProject_2)
        self.txtCreateProjectNama.setGeometry(QtCore.QRect(170, 150, 191, 41))
        self.txtCreateProjectNama.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtCreateProjectNama.setObjectName("txtCreateProjectNama")
        self.btCreateProjectKembali = QtWidgets.QPushButton(self.createProject_2)
        self.btCreateProjectKembali.setGeometry(QtCore.QRect(630, 50, 91, 41))
        self.btCreateProjectKembali.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.btCreateProjectKembali.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btCreateProjectKembali.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btCreateProjectKembali.setIconSize(QtCore.QSize(50, 50))
        self.btCreateProjectKembali.setFlat(False)
        self.btCreateProjectKembali.setObjectName("btCreateProjectKembali")
        self.txtCreateProjectCari = QtWidgets.QLineEdit(self.createProject_2)
        self.txtCreateProjectCari.setGeometry(QtCore.QRect(170, 290, 191, 41))
        self.txtCreateProjectCari.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtCreateProjectCari.setObjectName("txtCreateProjectCari")
        self.lbGetData_10 = QtWidgets.QLabel(self.createProject_2)
        self.lbGetData_10.setGeometry(QtCore.QRect(200, 130, 151, 17))
        self.lbGetData_10.setObjectName("lbGetData_10")
        self.label_51 = QtWidgets.QLabel(self.createProject_2)
        self.label_51.setGeometry(QtCore.QRect(40, 150, 121, 41))
        self.label_51.setStyleSheet(
            "QLabel {\n" "    font-size: 17px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.createProject_2)
        self.label_52.setGeometry(QtCore.QRect(40, 290, 101, 41))
        self.label_52.setStyleSheet(
            "QLabel {\n" "    font-size: 17px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_52.setObjectName("label_52")
        self.tbCreateProjectTabel = QtWidgets.QTableView(self.createProject_2)
        self.tbCreateProjectTabel.setGeometry(QtCore.QRect(40, 340, 801, 251))
        self.tbCreateProjectTabel.setObjectName("tbCreateProjectTabel")
        self.btCreateProjectCari = QtWidgets.QPushButton(self.createProject_2)
        self.btCreateProjectCari.setGeometry(QtCore.QRect(370, 290, 81, 41))
        self.btCreateProjectCari.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btCreateProjectCari.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btCreateProjectCari.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btCreateProjectCari.setIconSize(QtCore.QSize(50, 50))
        self.btCreateProjectCari.setFlat(False)
        self.btCreateProjectCari.setObjectName("btCreateProjectCari")
        self.lbGetData_11 = QtWidgets.QLabel(self.createProject_2)
        self.lbGetData_11.setGeometry(QtCore.QRect(690, 310, 151, 17))
        self.lbGetData_11.setStyleSheet(
            "QLabel {\n" "    font-size: 15px;\n" "    font-weight: bold;\n" "}"
        )
        self.lbGetData_11.setObjectName("lbGetData_11")
        self.btCreateProjectSimpan = QtWidgets.QPushButton(self.createProject_2)
        self.btCreateProjectSimpan.setGeometry(QtCore.QRect(730, 50, 91, 41))
        self.btCreateProjectSimpan.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.btCreateProjectSimpan.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btCreateProjectSimpan.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btCreateProjectSimpan.setIconSize(QtCore.QSize(50, 50))
        self.btCreateProjectSimpan.setFlat(False)
        self.btCreateProjectSimpan.setObjectName("btCreateProjectSimpan")

        self.txtCreateProjectKet = QtWidgets.QTextEdit(self.createProject_2)
        self.txtCreateProjectKet.setGeometry(QtCore.QRect(170, 200, 191, 81))
        self.txtCreateProjectKet.setStyleSheet(
            "QTextEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtCreateProjectKet.setObjectName("txtCreateProjectKet")
        self.label_53 = QtWidgets.QLabel(self.createProject_2)
        self.label_53.setGeometry(QtCore.QRect(40, 190, 121, 41))
        self.label_53.setStyleSheet(
            "QLabel {\n" "    font-size: 17px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_53.setObjectName("label_53")
        self.stackedWidget.addWidget(self.createProject_2)
        self.Integration_3 = QtWidgets.QWidget()
        self.Integration_3.setObjectName("Integration_3")
        self.label_6 = QtWidgets.QLabel(self.Integration_3)
        self.label_6.setGeometry(QtCore.QRect(190, 560, 16, 20))
        self.label_6.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-size: 20px;\n"
            "}"
        )
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.Integration_3)
        self.label_5.setGeometry(QtCore.QRect(110, 560, 16, 20))
        self.label_5.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-size: 20px;\n"
            "}"
        )
        self.label_5.setObjectName("label_5")
        self.txtIntegrationX = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationX.setGeometry(QtCore.QRect(90, 540, 51, 25))
        self.txtIntegrationX.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtIntegrationX.setObjectName("txtIntegrationX")
        self.frame_2 = QtWidgets.QFrame(self.Integration_3)
        self.frame_2.setGeometry(QtCore.QRect(30, 0, 821, 111))
        self.frame_2.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 341, 31))
        self.label_4.setStyleSheet(
            "QLabel {\n" "    font-size: 30px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_4.setObjectName("label_4")
        self.btIntegrationSimpan = QtWidgets.QPushButton(self.frame_2)
        self.btIntegrationSimpan.setGeometry(QtCore.QRect(700, 50, 81, 41))
        self.btIntegrationSimpan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btIntegrationSimpan.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btIntegrationSimpan.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btIntegrationSimpan.setIconSize(QtCore.QSize(50, 100))
        self.btIntegrationSimpan.setFlat(False)
        self.btIntegrationSimpan.setObjectName("btIntegrationSimpan")
        self.btIntegrationKembali = QtWidgets.QPushButton(self.frame_2)
        self.btIntegrationKembali.setGeometry(QtCore.QRect(610, 50, 81, 41))
        self.btIntegrationKembali.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btIntegrationKembali.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btIntegrationKembali.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btIntegrationKembali.setIconSize(QtCore.QSize(50, 100))
        self.btIntegrationKembali.setFlat(False)
        self.btIntegrationKembali.setObjectName("btIntegrationKembali")
        self.btBack_2 = QtWidgets.QPushButton(self.frame_2)
        self.btBack_2.setGeometry(QtCore.QRect(700, 154, 81, 41))
        self.btBack_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btBack_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btBack_2.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btBack_2.setIconSize(QtCore.QSize(50, 100))
        self.btBack_2.setFlat(False)
        self.btBack_2.setObjectName("btBack_2")
        self.btintegrationSetData = QtWidgets.QPushButton(self.Integration_3)
        self.btintegrationSetData.setGeometry(QtCore.QRect(60, 590, 81, 41))
        self.btintegrationSetData.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btintegrationSetData.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btintegrationSetData.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 16px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btintegrationSetData.setIconSize(QtCore.QSize(50, 100))
        self.btintegrationSetData.setFlat(False)
        self.btintegrationSetData.setObjectName("btintegrationSetData")
        self.tbIntegrationTabel = QtWidgets.QTableView(self.Integration_3)
        self.tbIntegrationTabel.setGeometry(QtCore.QRect(440, 180, 381, 441))
        self.tbIntegrationTabel.setObjectName("tbIntegrationTabel")
        self.txtIntegrationY = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationY.setGeometry(QtCore.QRect(170, 540, 51, 25))
        self.txtIntegrationY.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtIntegrationY.setObjectName("txtIntegrationY")
        self.label_7 = QtWidgets.QLabel(self.Integration_3)
        self.label_7.setGeometry(QtCore.QRect(90, 116, 131, 20))
        self.label_7.setStyleSheet(
            "QLabel {\n" "    font-weight: bold;\n" "    color: black;\n" "}"
        )
        self.label_7.setObjectName("label_7")
        self.txtIntegrationKet = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationKet.setGeometry(QtCore.QRect(90, 140, 301, 31))
        self.txtIntegrationKet.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-style:italic;\n"
            "}\n"
            ""
        )
        self.txtIntegrationKet.setText("")
        self.txtIntegrationKet.setObjectName("txtIntegrationKet")
        self.slIntegrationX = QtWidgets.QSlider(self.Integration_3)
        self.slIntegrationX.setGeometry(QtCore.QRect(100, 240, 31, 301))
        self.slIntegrationX.setStyleSheet(
            "QSlider::groove:vertical {\n"
            "        background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
            "                                    stop:0 #ddd, stop:1 #aaa);\n"
            "        border: 1px solid #bbb;\n"
            "        width: 10px;\n"
            "        border-radius: 5px;\n"
            "    }\n"
            "\n"
            "    QSlider::handle:vertical {\n"
            "        background: qradialgradient(cx:0, cy:0, cx:1, cy:1,\n"
            "                                    stop:0 #eee, stop:1 #ccc);\n"
            "        border: 1px solid #777;\n"
            "        width: 30px; \n"
            "        height: 30px; \n"
            "        margin: -15px -10px;\n"
            "        border-radius: 15px;\n"
            "    }"
        )
        self.slIntegrationX.setMaximum(700)
        self.slIntegrationX.setOrientation(QtCore.Qt.Vertical)
        self.slIntegrationX.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slIntegrationX.setTickInterval(5)
        self.slIntegrationX.setObjectName("slIntegrationX")
        self.label_8 = QtWidgets.QLabel(self.Integration_3)
        self.label_8.setGeometry(QtCore.QRect(270, 560, 16, 20))
        self.label_8.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-size: 20px;\n"
            "}"
        )
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.Integration_3)
        self.label_9.setGeometry(QtCore.QRect(350, 560, 16, 20))
        self.label_9.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-size: 20px;\n"
            "}"
        )
        self.label_9.setObjectName("label_9")
        self.slIntegrationZ = QtWidgets.QSlider(self.Integration_3)
        self.slIntegrationZ.setGeometry(QtCore.QRect(260, 240, 31, 301))
        self.slIntegrationZ.setStyleSheet(
            "QSlider::groove:vertical {\n"
            "        background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
            "                                    stop:0 #ddd, stop:1 #aaa);\n"
            "        border: 1px solid #bbb;\n"
            "        width: 10px;\n"
            "        border-radius: 5px;\n"
            "    }\n"
            "\n"
            "    QSlider::handle:vertical {\n"
            "        background: qradialgradient(cx:0, cy:0, cx:1, cy:1,\n"
            "                                    stop:0 #eee, stop:1 #ccc);\n"
            "        border: 1px solid #777;\n"
            "        width: 30px; \n"
            "        height: 30px; \n"
            "        margin: -15px -10px;\n"
            "        border-radius: 15px;\n"
            "    }"
        )
        self.slIntegrationZ.setMaximum(180)
        self.slIntegrationZ.setOrientation(QtCore.Qt.Vertical)
        self.slIntegrationZ.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slIntegrationZ.setTickInterval(5)
        self.slIntegrationZ.setObjectName("slIntegrationZ")
        self.slIntegrationY = QtWidgets.QSlider(self.Integration_3)
        self.slIntegrationY.setGeometry(QtCore.QRect(180, 240, 31, 301))
        self.slIntegrationY.setStyleSheet(
            "QSlider::groove:vertical {\n"
            "        background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
            "                                    stop:0 #ddd, stop:1 #aaa);\n"
            "        border: 1px solid #bbb;\n"
            "        width: 10px;\n"
            "        border-radius: 5px;\n"
            "    }\n"
            "\n"
            "    QSlider::handle:vertical {\n"
            "        background: qradialgradient(cx:0, cy:0, cx:1, cy:1,\n"
            "                                    stop:0 #eee, stop:1 #ccc);\n"
            "        border: 1px solid #777;\n"
            "        width: 30px; \n"
            "        height: 30px; \n"
            "        margin: -15px -10px;\n"
            "        border-radius: 15px;\n"
            "    }"
        )
        self.slIntegrationY.setMaximum(3500)
        self.slIntegrationY.setOrientation(QtCore.Qt.Vertical)
        self.slIntegrationY.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slIntegrationY.setTickInterval(5)
        self.slIntegrationY.setObjectName("slIntegrationY")
        self.btIntegrationReset = QtWidgets.QPushButton(self.Integration_3)
        self.btIntegrationReset.setGeometry(QtCore.QRect(150, 590, 81, 41))
        self.btIntegrationReset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btIntegrationReset.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btIntegrationReset.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 16px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btIntegrationReset.setIconSize(QtCore.QSize(50, 100))
        self.btIntegrationReset.setFlat(False)
        self.btIntegrationReset.setObjectName("btIntegrationReset")
        self.txtIntegrationK = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationK.setGeometry(QtCore.QRect(330, 540, 51, 25))
        self.txtIntegrationK.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtIntegrationK.setObjectName("txtIntegrationK")
        self.label_10 = QtWidgets.QLabel(self.Integration_3)
        self.label_10.setGeometry(QtCore.QRect(440, 136, 91, 31))
        self.label_10.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-size: 16px;\n"
            "}"
        )
        self.label_10.setObjectName("label_10")
        self.btIntegrationEdit = QtWidgets.QPushButton(self.Integration_3)
        self.btIntegrationEdit.setGeometry(QtCore.QRect(240, 590, 81, 41))
        self.btIntegrationEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btIntegrationEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btIntegrationEdit.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 16px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btIntegrationEdit.setIconSize(QtCore.QSize(50, 100))
        self.btIntegrationEdit.setFlat(False)
        self.btIntegrationEdit.setObjectName("btIntegrationEdit")
        self.slIntegrationK = QtWidgets.QSlider(self.Integration_3)
        self.slIntegrationK.setGeometry(QtCore.QRect(340, 240, 31, 301))
        self.slIntegrationK.setStyleSheet(
            "QSlider::groove:vertical {\n"
            "        background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
            "                                    stop:0 #ddd, stop:1 #aaa);\n"
            "        border: 1px solid #bbb;\n"
            "        width: 10px;\n"
            "        border-radius: 5px;\n"
            "    }\n"
            "\n"
            "    QSlider::handle:vertical {\n"
            "        background: qradialgradient(cx:0, cy:0, cx:1, cy:1,\n"
            "                                    stop:0 #eee, stop:1 #ccc);\n"
            "        border: 1px solid #777;\n"
            "        width: 30px; \n"
            "        height: 30px; \n"
            "        margin: -15px -10px;\n"
            "        border-radius: 15px;\n"
            "    }"
        )
        self.slIntegrationK.setMaximum(850)
        self.slIntegrationK.setOrientation(QtCore.Qt.Vertical)
        self.slIntegrationK.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slIntegrationK.setTickInterval(5)
        self.slIntegrationK.setObjectName("slIntegrationK")
        self.txtIntegrationCari = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationCari.setGeometry(QtCore.QRect(540, 130, 191, 41))
        self.txtIntegrationCari.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtIntegrationCari.setObjectName("txtIntegrationCari")
        self.txtIntegrationZ = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationZ.setGeometry(QtCore.QRect(250, 540, 51, 25))
        self.txtIntegrationZ.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtIntegrationZ.setObjectName("txtIntegrationZ")
        self.btIntegrationCari = QtWidgets.QPushButton(self.Integration_3)
        self.btIntegrationCari.setGeometry(QtCore.QRect(740, 130, 81, 41))
        self.btIntegrationCari.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btIntegrationCari.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btIntegrationCari.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btIntegrationCari.setIconSize(QtCore.QSize(50, 100))
        self.btIntegrationCari.setFlat(False)
        self.btIntegrationCari.setObjectName("btIntegrationCari")
        self.txtIntegrationDelay = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationDelay.setGeometry(QtCore.QRect(90, 200, 241, 31))
        self.txtIntegrationDelay.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-style:italic;\n"
            "}\n"
            ""
        )
        self.txtIntegrationDelay.setText("")
        self.txtIntegrationDelay.setObjectName("txtIntegrationDelay")
        self.label_55 = QtWidgets.QLabel(self.Integration_3)
        self.label_55.setGeometry(QtCore.QRect(90, 180, 211, 20))
        self.label_55.setStyleSheet(
            "QLabel {\n" "    font-weight: bold;\n" "    color: black;\n" "}"
        )
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.Integration_3)
        self.label_56.setGeometry(QtCore.QRect(340, 200, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-style: italic;\n"
            '    font-family: "Times New Roman";\n'
            "}"
        )
        self.label_56.setObjectName("label_56")
        self.btIntegrationHapus = QtWidgets.QPushButton(self.Integration_3)
        self.btIntegrationHapus.setGeometry(QtCore.QRect(330, 590, 81, 41))
        self.btIntegrationHapus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btIntegrationHapus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btIntegrationHapus.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 16px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btIntegrationHapus.setIconSize(QtCore.QSize(50, 100))
        self.btIntegrationHapus.setFlat(False)
        self.btIntegrationHapus.setObjectName("btIntegrationHapus")
        self.stackedWidget.addWidget(self.Integration_3)
        self.saveActivity_4 = QtWidgets.QWidget()
        self.saveActivity_4.setObjectName("saveActivity_4")
        self.frame_8 = QtWidgets.QFrame(self.saveActivity_4)
        self.frame_8.setGeometry(QtCore.QRect(30, 0, 821, 111))
        self.frame_8.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_29 = QtWidgets.QLabel(self.frame_8)
        self.label_29.setGeometry(QtCore.QRect(20, 40, 191, 31))
        self.label_29.setStyleSheet(
            "QLabel {\n" "    font-size: 30px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.saveActivity_4)
        self.label_30.setGeometry(QtCore.QRect(40, 280, 101, 41))
        self.label_30.setStyleSheet(
            "QLabel {\n" "    font-size: 17px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_30.setObjectName("label_30")
        self.btSaveActivityCari = QtWidgets.QPushButton(self.saveActivity_4)
        self.btSaveActivityCari.setGeometry(QtCore.QRect(370, 280, 81, 41))
        self.btSaveActivityCari.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btSaveActivityCari.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btSaveActivityCari.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btSaveActivityCari.setIconSize(QtCore.QSize(50, 50))
        self.btSaveActivityCari.setFlat(False)
        self.btSaveActivityCari.setObjectName("btSaveActivityCari")
        self.tbSaveActivityTabel = QtWidgets.QTableView(self.saveActivity_4)
        self.tbSaveActivityTabel.setGeometry(QtCore.QRect(40, 330, 801, 291))
        self.tbSaveActivityTabel.setObjectName("tbSaveActivityTabel")
        self.txtSaveActivityTanggal = QtWidgets.QLabel(self.saveActivity_4)
        self.txtSaveActivityTanggal.setGeometry(QtCore.QRect(200, 130, 151, 17))
        self.txtSaveActivityTanggal.setObjectName("txtSaveActivityTanggal")
        self.btSaveActivityKembali = QtWidgets.QPushButton(self.saveActivity_4)
        self.btSaveActivityKembali.setGeometry(QtCore.QRect(630, 50, 91, 41))
        self.btSaveActivityKembali.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.btSaveActivityKembali.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btSaveActivityKembali.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btSaveActivityKembali.setIconSize(QtCore.QSize(50, 50))
        self.btSaveActivityKembali.setFlat(False)
        self.btSaveActivityKembali.setObjectName("btSaveActivityKembali")
        self.txtSaveActivityCari = QtWidgets.QLineEdit(self.saveActivity_4)
        self.txtSaveActivityCari.setGeometry(QtCore.QRect(170, 280, 191, 41))
        self.txtSaveActivityCari.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtSaveActivityCari.setObjectName("txtSaveActivityCari")
        self.txtSaveActivityNama = QtWidgets.QLineEdit(self.saveActivity_4)
        self.txtSaveActivityNama.setGeometry(QtCore.QRect(170, 150, 191, 41))
        self.txtSaveActivityNama.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtSaveActivityNama.setObjectName("txtSaveActivityNama")
        self.label_31 = QtWidgets.QLabel(self.saveActivity_4)
        self.label_31.setGeometry(QtCore.QRect(40, 150, 121, 41))
        self.label_31.setStyleSheet(
            "QLabel {\n" "    font-size: 17px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_31.setObjectName("label_31")
        self.lbGetData_5 = QtWidgets.QLabel(self.saveActivity_4)
        self.lbGetData_5.setGeometry(QtCore.QRect(690, 310, 151, 17))
        self.lbGetData_5.setStyleSheet(
            "QLabel {\n" "    font-size: 15px;\n" "    font-weight: bold;\n" "}"
        )
        self.lbGetData_5.setObjectName("lbGetData_5")
        self.btSaveActivitySimpan = QtWidgets.QPushButton(self.saveActivity_4)
        self.btSaveActivitySimpan.setGeometry(QtCore.QRect(730, 50, 91, 41))
        self.btSaveActivitySimpan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btSaveActivitySimpan.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btSaveActivitySimpan.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btSaveActivitySimpan.setIconSize(QtCore.QSize(50, 50))
        self.btSaveActivitySimpan.setFlat(False)
        self.btSaveActivitySimpan.setObjectName("btSaveActivitySimpan")
        self.label_54 = QtWidgets.QLabel(self.saveActivity_4)
        self.label_54.setGeometry(QtCore.QRect(40, 190, 121, 41))
        self.label_54.setStyleSheet(
            "QLabel {\n" "    font-size: 17px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_54.setObjectName("label_54")
        self.txtSaveActivityKet = QtWidgets.QTextEdit(self.saveActivity_4)
        self.txtSaveActivityKet.setGeometry(QtCore.QRect(170, 200, 191, 70))
        self.txtSaveActivityKet.setStyleSheet(
            "QTextEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtSaveActivityKet.setObjectName("txtSaveActivityKet")
        self.stackedWidget.addWidget(self.saveActivity_4)
        self.openProject_5 = QtWidgets.QWidget()
        self.openProject_5.setObjectName("openProject_5")
        self.tbOpenProjectTabel = QtWidgets.QTableView(self.openProject_5)
        self.tbOpenProjectTabel.setGeometry(QtCore.QRect(40, 260, 801, 351))
        self.tbOpenProjectTabel.setObjectName("tbOpenProjectTabel")
        self.txtOpenProjectGetData = QtWidgets.QLabel(self.openProject_5)
        self.txtOpenProjectGetData.setGeometry(QtCore.QRect(670, 210, 67, 17))
        self.txtOpenProjectGetData.setObjectName("txtOpenProjectGetData")
        self.pushButton_3 = QtWidgets.QPushButton(self.openProject_5)
        self.pushButton_3.setGeometry(QtCore.QRect(740, 50, 91, 41))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_3 = QtWidgets.QFrame(self.openProject_5)
        self.frame_3.setGeometry(QtCore.QRect(30, 0, 821, 111))
        self.frame_3.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(20, 40, 251, 31))
        self.label_12.setStyleSheet(
            "QLabel {\n" "    font-size: 30px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_12.setObjectName("label_12")
        self.btOpenProjectBuka = QtWidgets.QPushButton(self.openProject_5)
        self.btOpenProjectBuka.setGeometry(QtCore.QRect(740, 200, 91, 41))
        self.btOpenProjectBuka.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btOpenProjectBuka.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btOpenProjectBuka.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btOpenProjectBuka.setIconSize(QtCore.QSize(50, 50))
        self.btOpenProjectBuka.setFlat(False)
        self.btOpenProjectBuka.setObjectName("btOpenProjectBuka")
        self.btOpenProjectCari = QtWidgets.QPushButton(self.openProject_5)
        self.btOpenProjectCari.setGeometry(QtCore.QRect(380, 200, 91, 41))
        self.btOpenProjectCari.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btOpenProjectCari.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btOpenProjectCari.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btOpenProjectCari.setIconSize(QtCore.QSize(50, 50))
        self.btOpenProjectCari.setFlat(False)
        self.btOpenProjectCari.setObjectName("btOpenProjectCari")
        self.label_13 = QtWidgets.QLabel(self.openProject_5)
        self.label_13.setGeometry(QtCore.QRect(60, 200, 101, 41))
        self.label_13.setStyleSheet(
            "QLabel {\n" "    font-size: 17px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_13.setObjectName("label_13")
        self.btOpenProjectKembali = QtWidgets.QPushButton(self.openProject_5)
        self.btOpenProjectKembali.setGeometry(QtCore.QRect(740, 50, 91, 41))
        self.btOpenProjectKembali.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btOpenProjectKembali.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btOpenProjectKembali.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btOpenProjectKembali.setIconSize(QtCore.QSize(50, 50))
        self.btOpenProjectKembali.setFlat(False)
        self.btOpenProjectKembali.setObjectName("btOpenProjectKembali")
        self.txtOpenProjectCari = QtWidgets.QLineEdit(self.openProject_5)
        self.txtOpenProjectCari.setGeometry(QtCore.QRect(170, 200, 201, 41))
        self.txtOpenProjectCari.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtOpenProjectCari.setObjectName("txtOpenProjectCari")
        self.stackedWidget.addWidget(self.openProject_5)
        self.runProject_6 = QtWidgets.QWidget()
        self.runProject_6.setObjectName("runProject_6")
        self.txtRunningProjectGetData = QtWidgets.QLabel(self.runProject_6)
        self.txtRunningProjectGetData.setGeometry(QtCore.QRect(670, 210, 67, 17))
        self.txtRunningProjectGetData.setObjectName("txtRunningProjectGetData")
        self.tbRunningProjectTabel = QtWidgets.QTableView(self.runProject_6)
        self.tbRunningProjectTabel.setGeometry(QtCore.QRect(40, 260, 801, 351))
        self.tbRunningProjectTabel.setObjectName("tbRunningProjectTabel")
        self.btRunningProjectCari = QtWidgets.QPushButton(self.runProject_6)
        self.btRunningProjectCari.setGeometry(QtCore.QRect(370, 200, 91, 41))
        self.btRunningProjectCari.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btRunningProjectCari.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunningProjectCari.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunningProjectCari.setIconSize(QtCore.QSize(50, 50))
        self.btRunningProjectCari.setFlat(False)
        self.btRunningProjectCari.setObjectName("btRunningProjectCari")
        self.label_27 = QtWidgets.QLabel(self.runProject_6)
        self.label_27.setGeometry(QtCore.QRect(60, 200, 101, 41))
        self.label_27.setStyleSheet(
            "QLabel {\n" "    font-size: 17px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_27.setObjectName("label_27")
        self.frame_7 = QtWidgets.QFrame(self.runProject_6)
        self.frame_7.setGeometry(QtCore.QRect(30, 0, 821, 111))
        self.frame_7.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_28 = QtWidgets.QLabel(self.frame_7)
        self.label_28.setGeometry(QtCore.QRect(20, 40, 251, 31))
        self.label_28.setStyleSheet(
            "QLabel {\n" "    font-size: 30px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_28.setObjectName("label_28")
        self.btRunningProjectRun = QtWidgets.QPushButton(self.runProject_6)
        self.btRunningProjectRun.setGeometry(QtCore.QRect(740, 200, 91, 41))
        self.btRunningProjectRun.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btRunningProjectRun.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunningProjectRun.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunningProjectRun.setIconSize(QtCore.QSize(50, 50))
        self.btRunningProjectRun.setFlat(False)
        self.btRunningProjectRun.setObjectName("btRunningProjectRun")
        self.pushButton_11 = QtWidgets.QPushButton(self.runProject_6)
        self.pushButton_11.setGeometry(QtCore.QRect(740, 50, 91, 41))
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_11.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.pushButton_11.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_11.setFlat(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.btRunningProjectKembali = QtWidgets.QPushButton(self.runProject_6)
        self.btRunningProjectKembali.setGeometry(QtCore.QRect(740, 50, 91, 41))
        self.btRunningProjectKembali.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.btRunningProjectKembali.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunningProjectKembali.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunningProjectKembali.setIconSize(QtCore.QSize(50, 50))
        self.btRunningProjectKembali.setFlat(False)
        self.btRunningProjectKembali.setObjectName("btRunningProjectKembali")
        self.txtRunningProjectCari = QtWidgets.QLineEdit(self.runProject_6)
        self.txtRunningProjectCari.setGeometry(QtCore.QRect(170, 200, 191, 41))
        self.txtRunningProjectCari.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtRunningProjectCari.setObjectName("txtRunningProjectCari")
        self.stackedWidget.addWidget(self.runProject_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btToGetStarted.setText(_translate("MainWindow", "Create Project"))
        self.label_2.setText(_translate("MainWindow", "OR"))
        self.btRunning.setText(_translate("MainWindow", "Open Project"))
        self.label.setText(_translate("MainWindow", "Welcome to RPA Integration"))
        self.btRunning_2.setText(_translate("MainWindow", "Logout"))
        self.btRunning_3.setText(_translate("MainWindow", "Restart"))
        self.btRunning_5.setText(_translate("MainWindow", "Running"))
        self.label_11.setText(_translate("MainWindow", "OR"))
        self.label_50.setText(_translate("MainWindow", "Create Project"))
        self.btCreateProjectKembali.setText(_translate("MainWindow", "Back"))
        self.lbGetData_10.setText(_translate("MainWindow", "$getCurrentDate"))
        self.label_51.setText(_translate("MainWindow", "Project name"))
        self.label_52.setText(_translate("MainWindow", "Search Data"))
        self.btCreateProjectCari.setText(_translate("MainWindow", "Search"))
        self.lbGetData_11.setText(_translate("MainWindow", "Project List Item"))
        self.btCreateProjectSimpan.setText(_translate("MainWindow", "Save"))
        self.label_53.setText(_translate("MainWindow", "Description"))
        self.label_6.setText(_translate("MainWindow", "y"))
        self.label_5.setText(_translate("MainWindow", "x"))
        self.label_4.setText(_translate("MainWindow", "INTEGRATION ROBOT"))
        self.btIntegrationSimpan.setText(_translate("MainWindow", "Save"))
        self.btIntegrationKembali.setText(_translate("MainWindow", "Back"))
        self.btBack_2.setText(_translate("MainWindow", "Back"))
        self.btintegrationSetData.setText(_translate("MainWindow", "Set Data"))
        self.label_7.setText(_translate("MainWindow", "Insert Description"))
        self.txtIntegrationKet.setPlaceholderText(
            _translate("MainWindow", "Please insert description now**")
        )
        self.label_8.setText(_translate("MainWindow", "z"))
        self.label_9.setText(_translate("MainWindow", "k"))
        self.btIntegrationReset.setText(_translate("MainWindow", "Reset"))
        self.label_10.setText(_translate("MainWindow", "Search Data"))
        self.btIntegrationEdit.setText(_translate("MainWindow", "Edit"))
        self.btIntegrationCari.setText(_translate("MainWindow", "Search"))
        self.txtIntegrationDelay.setPlaceholderText(
            _translate("MainWindow", "Insert delay if you needed")
        )
        self.label_55.setText(_translate("MainWindow", "Insert Delay Process"))
        self.label_56.setText(_translate("MainWindow", "Per m/s"))
        self.btIntegrationHapus.setText(_translate("MainWindow", "Delete"))
        self.label_29.setText(_translate("MainWindow", "Save Activity"))
        self.label_30.setText(_translate("MainWindow", "Search Data"))
        self.btSaveActivityCari.setText(_translate("MainWindow", "Search"))
        self.txtSaveActivityTanggal.setText(_translate("MainWindow", "$getCurrentDate"))
        self.btSaveActivityKembali.setText(_translate("MainWindow", "Back"))
        self.label_31.setText(_translate("MainWindow", "Activity Name"))
        self.lbGetData_5.setText(_translate("MainWindow", "Activity List Item"))
        self.btSaveActivitySimpan.setText(_translate("MainWindow", "Save"))
        self.label_54.setText(_translate("MainWindow", "Description"))
        self.txtOpenProjectGetData.setText(_translate("MainWindow", "$getData"))
        self.pushButton_3.setText(_translate("MainWindow", "Back"))
        self.label_12.setText(_translate("MainWindow", "Open Project"))
        self.btOpenProjectBuka.setText(_translate("MainWindow", "Open"))
        self.btOpenProjectCari.setText(_translate("MainWindow", "Search"))
        self.label_13.setText(_translate("MainWindow", "Search Data"))
        self.btOpenProjectKembali.setText(_translate("MainWindow", "Back"))
        self.txtRunningProjectGetData.setText(_translate("MainWindow", "$getData"))
        self.btRunningProjectCari.setText(_translate("MainWindow", "Search"))
        self.label_27.setText(_translate("MainWindow", "Search Data"))
        self.label_28.setText(_translate("MainWindow", "Running Project"))
        self.btRunningProjectRun.setText(_translate("MainWindow", "Run"))
        self.pushButton_11.setText(_translate("MainWindow", "Back"))
        self.btRunningProjectKembali.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized(1200)
    MainWindow.show()
    # index_dashboard_1 = ui.stackedWidget.indexOf(ui.dashboard_1)
    # ui.stackedWidget.setCurrentIndex(index_dashboard_1)
    # ui.btToGetStarted.clicked.connect(setGetStarted)
    # ui.btCreateProjectKembali.clicked.connect(setDashboard)
    # ui.btCreateProjectSimpan.clicked.connect(ui.setProyek)
    sys.exit(app.exec_())
