# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1287, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-20, 0, 1311, 700))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.stackedWidget.sizePolicy().hasHeightForWidth()
        )
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard_1 = QtWidgets.QWidget()
        self.dashboard_1.setObjectName("dashboard_1")
        self.btToGetStarted = QtWidgets.QPushButton(self.dashboard_1)
        self.btToGetStarted.setGeometry(QtCore.QRect(210, 220, 271, 271))
        self.btToGetStarted.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btToGetStarted.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btToGetStarted.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 135px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 35px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            ""
        )
        self.btToGetStarted.setIconSize(QtCore.QSize(50, 50))
        self.btToGetStarted.setFlat(False)
        self.btToGetStarted.setObjectName("btToGetStarted")
        self.btRunning = QtWidgets.QPushButton(self.dashboard_1)
        self.btRunning.setGeometry(QtCore.QRect(510, 220, 271, 271))
        self.btRunning.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btRunning.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunning.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 135px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 40px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunning.setIconSize(QtCore.QSize(50, 50))
        self.btRunning.setFlat(False)
        self.btRunning.setObjectName("btRunning")
        self.frame = QtWidgets.QFrame(self.dashboard_1)
        self.frame.setGeometry(QtCore.QRect(20, 0, 1321, 111))
        self.frame.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 40, 431, 31))
        self.label.setStyleSheet(
            "QLabel {\n" "    font-size: 30px;\n" "    font-weight: bold;\n" "}"
        )
        self.label.setObjectName("label")
        self.btLogout = QtWidgets.QPushButton(self.frame)
        self.btLogout.setGeometry(QtCore.QRect(1140, 30, 111, 61))
        self.btLogout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btLogout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btLogout.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 25px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btLogout.setIconSize(QtCore.QSize(50, 50))
        self.btLogout.setFlat(False)
        self.btLogout.setObjectName("btLogout")
        self.btRestart = QtWidgets.QPushButton(self.frame)
        self.btRestart.setGeometry(QtCore.QRect(1010, 30, 111, 61))
        self.btRestart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btRestart.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRestart.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 25px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRestart.setIconSize(QtCore.QSize(50, 50))
        self.btRestart.setFlat(False)
        self.btRestart.setObjectName("btRestart")
        self.btRunning_2 = QtWidgets.QPushButton(self.dashboard_1)
        self.btRunning_2.setGeometry(QtCore.QRect(810, 220, 271, 271))
        self.btRunning_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btRunning_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunning_2.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 135px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 40px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunning_2.setIconSize(QtCore.QSize(50, 50))
        self.btRunning_2.setFlat(False)
        self.btRunning_2.setObjectName("btRunning_2")
        self.stackedWidget.addWidget(self.dashboard_1)
        self.createProject_2 = QtWidgets.QWidget()
        self.createProject_2.setObjectName("createProject_2")
        self.frame_14 = QtWidgets.QFrame(self.createProject_2)
        self.frame_14.setGeometry(QtCore.QRect(20, 0, 1291, 111))
        self.frame_14.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_50 = QtWidgets.QLabel(self.frame_14)
        self.label_50.setGeometry(QtCore.QRect(20, 40, 211, 31))
        self.label_50.setStyleSheet(
            "QLabel {\n" "    font-size: 30px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_50.setObjectName("label_50")
        self.btCreateProjectKembali = QtWidgets.QPushButton(self.frame_14)
        self.btCreateProjectKembali.setGeometry(QtCore.QRect(1170, 50, 91, 41))
        self.btCreateProjectKembali.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.btCreateProjectKembali.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btCreateProjectKembali.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btCreateProjectKembali.setIconSize(QtCore.QSize(50, 50))
        self.btCreateProjectKembali.setFlat(False)
        self.btCreateProjectKembali.setObjectName("btCreateProjectKembali")
        self.txtCreateProjectNama = QtWidgets.QLineEdit(self.createProject_2)
        self.txtCreateProjectNama.setGeometry(QtCore.QRect(180, 170, 291, 51))
        self.txtCreateProjectNama.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-size: 20px\n"
            "}"
        )
        self.txtCreateProjectNama.setObjectName("txtCreateProjectNama")
        self.txtCreateProjectCari = QtWidgets.QLineEdit(self.createProject_2)
        self.txtCreateProjectCari.setGeometry(QtCore.QRect(620, 160, 331, 51))
        self.txtCreateProjectCari.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-size: 20px;\n"
            "}"
        )
        self.txtCreateProjectCari.setObjectName("txtCreateProjectCari")
        self.lbCreateProjectKode = QtWidgets.QLabel(self.createProject_2)
        self.lbCreateProjectKode.setGeometry(QtCore.QRect(180, 140, 151, 17))
        self.lbCreateProjectKode.setObjectName("lbCreateProjectKode")
        self.label_51 = QtWidgets.QLabel(self.createProject_2)
        self.label_51.setGeometry(QtCore.QRect(40, 170, 131, 41))
        self.label_51.setStyleSheet(
            "QLabel {\n" "    font-size: 20px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.createProject_2)
        self.label_52.setGeometry(QtCore.QRect(490, 170, 121, 41))
        self.label_52.setStyleSheet(
            "QLabel {\n" "    font-size: 20px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_52.setObjectName("label_52")
        self.tbCreateProjectTabel = QtWidgets.QTableView(self.createProject_2)
        self.tbCreateProjectTabel.setGeometry(QtCore.QRect(490, 220, 811, 451))
        self.tbCreateProjectTabel.setObjectName("tbCreateProjectTabel")
        self.lbGetData_11 = QtWidgets.QLabel(self.createProject_2)
        self.lbGetData_11.setGeometry(QtCore.QRect(1150, 200, 151, 17))
        self.lbGetData_11.setStyleSheet(
            "QLabel {\n" "    font-size: 15px;\n" "    font-weight: bold;\n" "}"
        )
        self.lbGetData_11.setObjectName("lbGetData_11")
        self.btCreateProjectSimpan = QtWidgets.QPushButton(self.createProject_2)
        self.btCreateProjectSimpan.setGeometry(QtCore.QRect(170, 570, 301, 51))
        self.btCreateProjectSimpan.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.btCreateProjectSimpan.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btCreateProjectSimpan.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btCreateProjectSimpan.setIconSize(QtCore.QSize(50, 50))
        self.btCreateProjectSimpan.setFlat(False)
        self.btCreateProjectSimpan.setObjectName("btCreateProjectSimpan")
        self.txtCreateProjectKet = QtWidgets.QTextEdit(self.createProject_2)
        self.txtCreateProjectKet.setGeometry(QtCore.QRect(180, 230, 291, 331))
        self.txtCreateProjectKet.setStyleSheet(
            "QTextEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-size: 20px;\n"
            "}"
        )
        self.txtCreateProjectKet.setObjectName("txtCreateProjectKet")
        self.label_53 = QtWidgets.QLabel(self.createProject_2)
        self.label_53.setGeometry(QtCore.QRect(40, 220, 121, 41))
        self.label_53.setStyleSheet(
            "QLabel {\n" "    font-size: 20px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_53.setObjectName("label_53")
        self.stackedWidget.addWidget(self.createProject_2)
        self.Integration_3 = QtWidgets.QWidget()
        self.Integration_3.setObjectName("Integration_3")
        self.label_5 = QtWidgets.QLabel(self.Integration_3)
        self.label_5.setGeometry(QtCore.QRect(30, 640, 31, 31))
        self.label_5.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-size: 30px;\n"
            "}"
        )
        self.label_5.setObjectName("label_5")
        self.txtIntegrationX = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationX.setGeometry(QtCore.QRect(20, 610, 51, 31))
        self.txtIntegrationX.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtIntegrationX.setObjectName("txtIntegrationX")
        self.frame_2 = QtWidgets.QFrame(self.Integration_3)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 671, 111))
        self.frame_2.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(30, 40, 341, 31))
        self.label_4.setStyleSheet(
            "QLabel {\n" "    font-size: 30px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_4.setObjectName("label_4")
        self.btIntegrationSimpan = QtWidgets.QPushButton(self.frame_2)
        self.btIntegrationSimpan.setGeometry(QtCore.QRect(550, 30, 91, 61))
        self.btIntegrationSimpan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btIntegrationSimpan.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btIntegrationSimpan.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btIntegrationSimpan.setIconSize(QtCore.QSize(50, 100))
        self.btIntegrationSimpan.setFlat(False)
        self.btIntegrationSimpan.setObjectName("btIntegrationSimpan")
        self.btIntegrationKembali = QtWidgets.QPushButton(self.frame_2)
        self.btIntegrationKembali.setGeometry(QtCore.QRect(440, 30, 91, 61))
        self.btIntegrationKembali.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btIntegrationKembali.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btIntegrationKembali.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btIntegrationKembali.setIconSize(QtCore.QSize(50, 100))
        self.btIntegrationKembali.setFlat(False)
        self.btIntegrationKembali.setObjectName("btIntegrationKembali")
        self.btBack_2 = QtWidgets.QPushButton(self.frame_2)
        self.btBack_2.setGeometry(QtCore.QRect(700, 154, 81, 41))
        self.btBack_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btBack_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btBack_2.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btBack_2.setIconSize(QtCore.QSize(50, 100))
        self.btBack_2.setFlat(False)
        self.btBack_2.setObjectName("btBack_2")
        self.btintegrationSetData = QtWidgets.QPushButton(self.Integration_3)
        self.btintegrationSetData.setGeometry(QtCore.QRect(360, 340, 301, 51))
        self.btintegrationSetData.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btintegrationSetData.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btintegrationSetData.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 22px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btintegrationSetData.setIconSize(QtCore.QSize(50, 100))
        self.btintegrationSetData.setFlat(False)
        self.btintegrationSetData.setObjectName("btintegrationSetData")
        self.tbIntegrationTabel = QtWidgets.QTableView(self.Integration_3)
        self.tbIntegrationTabel.setGeometry(QtCore.QRect(680, 150, 591, 521))
        self.tbIntegrationTabel.setObjectName("tbIntegrationTabel")
        self.txtIntegrationY = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationY.setGeometry(QtCore.QRect(110, 610, 51, 31))
        self.txtIntegrationY.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtIntegrationY.setObjectName("txtIntegrationY")
        self.label_7 = QtWidgets.QLabel(self.Integration_3)
        self.label_7.setGeometry(QtCore.QRect(360, 140, 231, 20))
        self.label_7.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-size: 22px;\n"
            "}"
        )
        self.label_7.setObjectName("label_7")
        self.txtIntegrationKet = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationKet.setGeometry(QtCore.QRect(360, 170, 301, 51))
        self.txtIntegrationKet.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-style:italic;\n"
            "    font-size: 22px;\n"
            "}\n"
            ""
        )
        self.txtIntegrationKet.setText("")
        self.txtIntegrationKet.setObjectName("txtIntegrationKet")
        self.slIntegrationX = QtWidgets.QSlider(self.Integration_3)
        self.slIntegrationX.setGeometry(QtCore.QRect(30, 230, 31, 381))
        self.slIntegrationX.setStyleSheet(
            "QSlider::groove:vertical {\n"
            "        background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
            "                                    stop:0 #ddd, stop:1 #aaa);\n"
            "        border: 1px solid #bbb;\n"
            "        width: 10px;\n"
            "        border-radius: 5px;\n"
            "    }\n"
            "\n"
            "    QSlider::handle:vertical {\n"
            "        background: qradialgradient(cx:0, cy:0, cx:1, cy:1,\n"
            "                                    stop:0 #eee, stop:1 #ccc);\n"
            "        border: 1px solid #777;\n"
            "        width: 30px; \n"
            "        height: 30px; \n"
            "        margin: -15px -10px;\n"
            "        border-radius: 15px;\n"
            "    }"
        )
        self.slIntegrationX.setMaximum(700)
        self.slIntegrationX.setOrientation(QtCore.Qt.Vertical)
        self.slIntegrationX.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slIntegrationX.setTickInterval(5)
        self.slIntegrationX.setObjectName("slIntegrationX")
        self.slIntegrationZ = QtWidgets.QSlider(self.Integration_3)
        self.slIntegrationZ.setGeometry(QtCore.QRect(210, 230, 31, 381))
        self.slIntegrationZ.setStyleSheet(
            "QSlider::groove:vertical {\n"
            "        background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
            "                                    stop:0 #ddd, stop:1 #aaa);\n"
            "        border: 1px solid #bbb;\n"
            "        width: 10px;\n"
            "        border-radius: 5px;\n"
            "    }\n"
            "\n"
            "    QSlider::handle:vertical {\n"
            "        background: qradialgradient(cx:0, cy:0, cx:1, cy:1,\n"
            "                                    stop:0 #eee, stop:1 #ccc);\n"
            "        border: 1px solid #777;\n"
            "        width: 30px; \n"
            "        height: 30px; \n"
            "        margin: -15px -10px;\n"
            "        border-radius: 15px;\n"
            "    }"
        )
        self.slIntegrationZ.setMaximum(180)
        self.slIntegrationZ.setOrientation(QtCore.Qt.Vertical)
        self.slIntegrationZ.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slIntegrationZ.setTickInterval(5)
        self.slIntegrationZ.setObjectName("slIntegrationZ")
        self.slIntegrationY = QtWidgets.QSlider(self.Integration_3)
        self.slIntegrationY.setGeometry(QtCore.QRect(120, 230, 31, 381))
        self.slIntegrationY.setStyleSheet(
            "QSlider::groove:vertical {\n"
            "        background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
            "                                    stop:0 #ddd, stop:1 #aaa);\n"
            "        border: 1px solid #bbb;\n"
            "        width: 10px;\n"
            "        border-radius: 5px;\n"
            "    }\n"
            "\n"
            "    QSlider::handle:vertical {\n"
            "        background: qradialgradient(cx:0, cy:0, cx:1, cy:1,\n"
            "                                    stop:0 #eee, stop:1 #ccc);\n"
            "        border: 1px solid #777;\n"
            "        width: 30px; \n"
            "        height: 30px; \n"
            "        margin: -15px -10px;\n"
            "        border-radius: 15px;\n"
            "    }"
        )
        self.slIntegrationY.setMaximum(3500)
        self.slIntegrationY.setOrientation(QtCore.Qt.Vertical)
        self.slIntegrationY.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slIntegrationY.setTickInterval(5)
        self.slIntegrationY.setObjectName("slIntegrationY")
        self.btIntegrationReset = QtWidgets.QPushButton(self.Integration_3)
        self.btIntegrationReset.setGeometry(QtCore.QRect(360, 400, 301, 51))
        self.btIntegrationReset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btIntegrationReset.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btIntegrationReset.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 22px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btIntegrationReset.setIconSize(QtCore.QSize(50, 100))
        self.btIntegrationReset.setFlat(False)
        self.btIntegrationReset.setObjectName("btIntegrationReset")
        self.txtIntegrationK = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationK.setGeometry(QtCore.QRect(290, 610, 51, 31))
        self.txtIntegrationK.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtIntegrationK.setObjectName("txtIntegrationK")
        self.btIntegrationEdit = QtWidgets.QPushButton(self.Integration_3)
        self.btIntegrationEdit.setGeometry(QtCore.QRect(360, 460, 301, 51))
        self.btIntegrationEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btIntegrationEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btIntegrationEdit.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 22px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btIntegrationEdit.setIconSize(QtCore.QSize(50, 100))
        self.btIntegrationEdit.setFlat(False)
        self.btIntegrationEdit.setObjectName("btIntegrationEdit")
        self.slIntegrationK = QtWidgets.QSlider(self.Integration_3)
        self.slIntegrationK.setGeometry(QtCore.QRect(300, 230, 31, 381))
        self.slIntegrationK.setStyleSheet(
            "QSlider::groove:vertical {\n"
            "        background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
            "                                    stop:0 #ddd, stop:1 #aaa);\n"
            "        border: 1px solid #bbb;\n"
            "        width: 10px;\n"
            "        border-radius: 5px;\n"
            "    }\n"
            "\n"
            "    QSlider::handle:vertical {\n"
            "        background: qradialgradient(cx:0, cy:0, cx:1, cy:1,\n"
            "                                    stop:0 #eee, stop:1 #ccc);\n"
            "        border: 1px solid #777;\n"
            "        width: 30px; \n"
            "        height: 30px; \n"
            "        margin: -15px -10px;\n"
            "        border-radius: 15px;\n"
            "    }"
        )
        self.slIntegrationK.setMaximum(850)
        self.slIntegrationK.setOrientation(QtCore.Qt.Vertical)
        self.slIntegrationK.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slIntegrationK.setTickInterval(5)
        self.slIntegrationK.setObjectName("slIntegrationK")
        self.txtIntegrationZ = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationZ.setGeometry(QtCore.QRect(200, 610, 51, 31))
        self.txtIntegrationZ.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "}"
        )
        self.txtIntegrationZ.setObjectName("txtIntegrationZ")
        self.txtIntegrationDelay = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationDelay.setGeometry(QtCore.QRect(360, 270, 301, 51))
        self.txtIntegrationDelay.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-style:italic;\n"
            "    font-size: 22px;\n"
            "}\n"
            ""
        )
        self.txtIntegrationDelay.setText("")
        self.txtIntegrationDelay.setObjectName("txtIntegrationDelay")
        self.label_55 = QtWidgets.QLabel(self.Integration_3)
        self.label_55.setGeometry(QtCore.QRect(360, 240, 211, 20))
        self.label_55.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-size: 22px;\n"
            "}"
        )
        self.label_55.setObjectName("label_55")
        self.btIntegrationHapus = QtWidgets.QPushButton(self.Integration_3)
        self.btIntegrationHapus.setGeometry(QtCore.QRect(360, 520, 301, 51))
        self.btIntegrationHapus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btIntegrationHapus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btIntegrationHapus.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 22px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btIntegrationHapus.setIconSize(QtCore.QSize(50, 100))
        self.btIntegrationHapus.setFlat(False)
        self.btIntegrationHapus.setObjectName("btIntegrationHapus")
        self.frame_4 = QtWidgets.QFrame(self.Integration_3)
        self.frame_4.setGeometry(QtCore.QRect(680, -1, 631, 111))
        self.frame_4.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(20, 50, 131, 31))
        self.label_10.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: white;\n"
            "    font-size: 22px;\n"
            "}"
        )
        self.label_10.setObjectName("label_10")
        self.txtIntegrationCari = QtWidgets.QLineEdit(self.frame_4)
        self.txtIntegrationCari.setGeometry(QtCore.QRect(160, 40, 261, 51))
        self.txtIntegrationCari.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-size: 22px;\n"
            "}"
        )
        self.txtIntegrationCari.setObjectName("txtIntegrationCari")
        self.btIntegrationCari = QtWidgets.QPushButton(self.frame_4)
        self.btIntegrationCari.setGeometry(QtCore.QRect(430, 40, 81, 51))
        self.btIntegrationCari.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btIntegrationCari.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btIntegrationCari.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            "\n"
            ""
        )
        self.btIntegrationCari.setIconSize(QtCore.QSize(50, 100))
        self.btIntegrationCari.setFlat(False)
        self.btIntegrationCari.setObjectName("btIntegrationCari")
        self.label_11 = QtWidgets.QLabel(self.Integration_3)
        self.label_11.setGeometry(QtCore.QRect(890, 120, 181, 31))
        self.label_11.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-size: 22px;\n"
            "}"
        )
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(self.Integration_3)
        self.label_14.setGeometry(QtCore.QRect(30, 140, 231, 20))
        self.label_14.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-size: 22px;\n"
            "}"
        )
        self.label_14.setObjectName("label_14")
        self.txtIntegrationKet_2 = QtWidgets.QLineEdit(self.Integration_3)
        self.txtIntegrationKet_2.setEnabled(False)
        self.txtIntegrationKet_2.setGeometry(QtCore.QRect(30, 170, 301, 51))
        self.txtIntegrationKet_2.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-style:italic;\n"
            "    font-size: 22px;\n"
            "}\n"
            ""
        )
        self.txtIntegrationKet_2.setText("")
        self.txtIntegrationKet_2.setPlaceholderText("")
        self.txtIntegrationKet_2.setObjectName("txtIntegrationKet_2")
        self.label_6 = QtWidgets.QLabel(self.Integration_3)
        self.label_6.setGeometry(QtCore.QRect(120, 640, 31, 31))
        self.label_6.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-size: 30px;\n"
            "}"
        )
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.Integration_3)
        self.label_8.setGeometry(QtCore.QRect(210, 640, 31, 31))
        self.label_8.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-size: 30px;\n"
            "}"
        )
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.Integration_3)
        self.label_9.setGeometry(QtCore.QRect(300, 640, 31, 31))
        self.label_9.setStyleSheet(
            "QLabel {\n"
            "    font-weight: bold;\n"
            "    color: black;\n"
            "    font-size: 30px;\n"
            "}"
        )
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.Integration_3)
        self.saveActivity_4 = QtWidgets.QWidget()
        self.saveActivity_4.setObjectName("saveActivity_4")
        self.frame_8 = QtWidgets.QFrame(self.saveActivity_4)
        self.frame_8.setGeometry(QtCore.QRect(30, 0, 451, 111))
        self.frame_8.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_29 = QtWidgets.QLabel(self.frame_8)
        self.label_29.setGeometry(QtCore.QRect(20, 40, 191, 31))
        self.label_29.setStyleSheet(
            "QLabel {\n" "    font-size: 30px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_29.setObjectName("label_29")
        self.tbSaveActivityTabel = QtWidgets.QTableView(self.saveActivity_4)
        self.tbSaveActivityTabel.setGeometry(QtCore.QRect(500, 170, 851, 491))
        self.tbSaveActivityTabel.setObjectName("tbSaveActivityTabel")
        self.btSaveActivityKembali = QtWidgets.QPushButton(self.saveActivity_4)
        self.btSaveActivityKembali.setGeometry(QtCore.QRect(50, 600, 431, 51))
        self.btSaveActivityKembali.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.btSaveActivityKembali.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btSaveActivityKembali.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 25px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btSaveActivityKembali.setIconSize(QtCore.QSize(50, 50))
        self.btSaveActivityKembali.setFlat(False)
        self.btSaveActivityKembali.setObjectName("btSaveActivityKembali")
        self.txtSaveActivityNama = QtWidgets.QLineEdit(self.saveActivity_4)
        self.txtSaveActivityNama.setGeometry(QtCore.QRect(50, 280, 431, 51))
        self.txtSaveActivityNama.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-size: 20px;\n"
            "}\n"
            ""
        )
        self.txtSaveActivityNama.setObjectName("txtSaveActivityNama")
        self.label_31 = QtWidgets.QLabel(self.saveActivity_4)
        self.label_31.setGeometry(QtCore.QRect(50, 240, 171, 41))
        self.label_31.setStyleSheet(
            "QLabel {\n" "    font-size: 22px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_31.setObjectName("label_31")
        self.lbGetData_5 = QtWidgets.QLabel(self.saveActivity_4)
        self.lbGetData_5.setGeometry(QtCore.QRect(860, 140, 181, 31))
        self.lbGetData_5.setStyleSheet(
            "QLabel {\n" "    font-size: 22px;\n" "    font-weight: bold;\n" "}"
        )
        self.lbGetData_5.setObjectName("lbGetData_5")
        self.btSaveActivitySimpan = QtWidgets.QPushButton(self.saveActivity_4)
        self.btSaveActivitySimpan.setGeometry(QtCore.QRect(50, 540, 431, 51))
        self.btSaveActivitySimpan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btSaveActivitySimpan.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btSaveActivitySimpan.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 25px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btSaveActivitySimpan.setIconSize(QtCore.QSize(50, 50))
        self.btSaveActivitySimpan.setFlat(False)
        self.btSaveActivitySimpan.setObjectName("btSaveActivitySimpan")
        self.label_54 = QtWidgets.QLabel(self.saveActivity_4)
        self.label_54.setGeometry(QtCore.QRect(50, 330, 121, 41))
        self.label_54.setStyleSheet(
            "QLabel {\n" "    font-size: 22px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_54.setObjectName("label_54")
        self.txtSaveActivityKet = QtWidgets.QTextEdit(self.saveActivity_4)
        self.txtSaveActivityKet.setGeometry(QtCore.QRect(50, 370, 431, 161))
        self.txtSaveActivityKet.setStyleSheet(
            "QTextEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-size: 20px;\n"
            "}"
        )
        self.txtSaveActivityKet.setObjectName("txtSaveActivityKet")
        self.frame_5 = QtWidgets.QFrame(self.saveActivity_4)
        self.frame_5.setGeometry(QtCore.QRect(500, 0, 811, 111))
        self.frame_5.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.btSaveActivityCari = QtWidgets.QPushButton(self.frame_5)
        self.btSaveActivityCari.setGeometry(QtCore.QRect(480, 40, 101, 51))
        self.btSaveActivityCari.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btSaveActivityCari.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btSaveActivityCari.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 25px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btSaveActivityCari.setIconSize(QtCore.QSize(50, 50))
        self.btSaveActivityCari.setFlat(False)
        self.btSaveActivityCari.setObjectName("btSaveActivityCari")
        self.label_30 = QtWidgets.QLabel(self.frame_5)
        self.label_30.setGeometry(QtCore.QRect(10, 40, 151, 51))
        self.label_30.setStyleSheet(
            "QLabel {\n" "    font-size: 22px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_30.setObjectName("label_30")
        self.txtSaveActivityCari = QtWidgets.QLineEdit(self.frame_5)
        self.txtSaveActivityCari.setGeometry(QtCore.QRect(160, 40, 301, 51))
        self.txtSaveActivityCari.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-size: 20px;\n"
            "}"
        )
        self.txtSaveActivityCari.setObjectName("txtSaveActivityCari")
        self.label_32 = QtWidgets.QLabel(self.saveActivity_4)
        self.label_32.setGeometry(QtCore.QRect(50, 150, 161, 41))
        self.label_32.setStyleSheet(
            "QLabel {\n" "    font-size: 22px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_32.setObjectName("label_32")
        self.txtSaveActivityNama_2 = QtWidgets.QLineEdit(self.saveActivity_4)
        self.txtSaveActivityNama_2.setGeometry(QtCore.QRect(50, 190, 291, 51))
        self.txtSaveActivityNama_2.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-size: 20px;\n"
            "}"
        )
        self.txtSaveActivityNama_2.setObjectName("txtSaveActivityNama_2")
        self.stackedWidget.addWidget(self.saveActivity_4)
        self.openProject_5 = QtWidgets.QWidget()
        self.openProject_5.setObjectName("openProject_5")
        self.tbOpenProjectTabel = QtWidgets.QTableView(self.openProject_5)
        self.tbOpenProjectTabel.setGeometry(QtCore.QRect(30, 260, 1271, 351))
        self.tbOpenProjectTabel.setObjectName("tbOpenProjectTabel")
        self.txtOpenProjectGetData = QtWidgets.QLabel(self.openProject_5)
        self.txtOpenProjectGetData.setGeometry(QtCore.QRect(1030, 210, 121, 31))
        self.txtOpenProjectGetData.setStyleSheet(
            "QLabel {\n"
            "    font-size: 20px;\n"
            "    color: black;\n"
            "    font-weight: bold;\n"
            "}"
        )
        self.txtOpenProjectGetData.setObjectName("txtOpenProjectGetData")
        self.pushButton_3 = QtWidgets.QPushButton(self.openProject_5)
        self.pushButton_3.setGeometry(QtCore.QRect(740, 50, 91, 41))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_3 = QtWidgets.QFrame(self.openProject_5)
        self.frame_3.setGeometry(QtCore.QRect(30, 0, 1281, 111))
        self.frame_3.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(20, 40, 251, 31))
        self.label_12.setStyleSheet(
            "QLabel {\n" "    font-size: 30px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_12.setObjectName("label_12")
        self.btOpenProjectKembali = QtWidgets.QPushButton(self.frame_3)
        self.btOpenProjectKembali.setGeometry(QtCore.QRect(1130, 30, 111, 51))
        self.btOpenProjectKembali.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btOpenProjectKembali.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btOpenProjectKembali.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 22px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btOpenProjectKembali.setIconSize(QtCore.QSize(50, 50))
        self.btOpenProjectKembali.setFlat(False)
        self.btOpenProjectKembali.setObjectName("btOpenProjectKembali")
        self.btOpenProjectBuka = QtWidgets.QPushButton(self.openProject_5)
        self.btOpenProjectBuka.setGeometry(QtCore.QRect(1160, 200, 101, 51))
        self.btOpenProjectBuka.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btOpenProjectBuka.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btOpenProjectBuka.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 22px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btOpenProjectBuka.setIconSize(QtCore.QSize(50, 50))
        self.btOpenProjectBuka.setFlat(False)
        self.btOpenProjectBuka.setObjectName("btOpenProjectBuka")
        self.btOpenProjectCari = QtWidgets.QPushButton(self.openProject_5)
        self.btOpenProjectCari.setGeometry(QtCore.QRect(490, 200, 101, 51))
        self.btOpenProjectCari.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btOpenProjectCari.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btOpenProjectCari.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 25px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btOpenProjectCari.setIconSize(QtCore.QSize(50, 50))
        self.btOpenProjectCari.setFlat(False)
        self.btOpenProjectCari.setObjectName("btOpenProjectCari")
        self.label_13 = QtWidgets.QLabel(self.openProject_5)
        self.label_13.setGeometry(QtCore.QRect(60, 200, 131, 41))
        self.label_13.setStyleSheet(
            "QLabel {\n" "    font-size: 22px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_13.setObjectName("label_13")
        self.txtOpenProjectCari = QtWidgets.QLineEdit(self.openProject_5)
        self.txtOpenProjectCari.setGeometry(QtCore.QRect(200, 200, 281, 51))
        self.txtOpenProjectCari.setStyleSheet(
            "QLineEdit {\n"
            "    border-radius: 10px;\n"
            "    border: 3px solid black;\n"
            "    font-size: 22px;\n"
            "}"
        )
        self.txtOpenProjectCari.setObjectName("txtOpenProjectCari")
        self.stackedWidget.addWidget(self.openProject_5)
        self.runProject_6 = QtWidgets.QWidget()
        self.runProject_6.setObjectName("runProject_6")
        self.txtRunningProjectGetData = QtWidgets.QLabel(self.runProject_6)
        self.txtRunningProjectGetData.setGeometry(QtCore.QRect(1120, 230, 67, 17))
        self.txtRunningProjectGetData.setObjectName("txtRunningProjectGetData")
        self.tbRunningProjectTabel = QtWidgets.QTableView(self.runProject_6)
        self.tbRunningProjectTabel.setGeometry(QtCore.QRect(40, 280, 551, 411))
        self.tbRunningProjectTabel.setObjectName("tbRunningProjectTabel")
        self.btRunningProjectCari = QtWidgets.QPushButton(self.runProject_6)
        self.btRunningProjectCari.setGeometry(QtCore.QRect(500, 200, 91, 51))
        self.btRunningProjectCari.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btRunningProjectCari.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunningProjectCari.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunningProjectCari.setIconSize(QtCore.QSize(50, 50))
        self.btRunningProjectCari.setFlat(False)
        self.btRunningProjectCari.setObjectName("btRunningProjectCari")
        self.label_27 = QtWidgets.QLabel(self.runProject_6)
        self.label_27.setGeometry(QtCore.QRect(40, 210, 141, 41))
        self.label_27.setStyleSheet(
            "QLabel {\n" "    font-size: 22px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_27.setObjectName("label_27")
        self.frame_7 = QtWidgets.QFrame(self.runProject_6)
        self.frame_7.setGeometry(QtCore.QRect(20, 0, 1291, 111))
        self.frame_7.setStyleSheet(
            "QFrame {\n"
            "    background-color: rgb(204, 0, 0);\n"
            "    color: white;\n"
            "}"
        )
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_28 = QtWidgets.QLabel(self.frame_7)
        self.label_28.setGeometry(QtCore.QRect(20, 30, 331, 51))
        self.label_28.setStyleSheet(
            "QLabel {\n" "    font-size: 40px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_28.setObjectName("label_28")
        self.btRunningProjectKembali = QtWidgets.QPushButton(self.frame_7)
        self.btRunningProjectKembali.setGeometry(QtCore.QRect(1160, 30, 101, 51))
        self.btRunningProjectKembali.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.btRunningProjectKembali.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunningProjectKembali.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunningProjectKembali.setIconSize(QtCore.QSize(50, 50))
        self.btRunningProjectKembali.setFlat(False)
        self.btRunningProjectKembali.setObjectName("btRunningProjectKembali")
        self.btRunningProjectRun = QtWidgets.QPushButton(self.runProject_6)
        self.btRunningProjectRun.setGeometry(QtCore.QRect(1200, 210, 91, 51))
        self.btRunningProjectRun.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btRunningProjectRun.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunningProjectRun.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunningProjectRun.setIconSize(QtCore.QSize(50, 50))
        self.btRunningProjectRun.setFlat(False)
        self.btRunningProjectRun.setObjectName("btRunningProjectRun")
        self.tbRunningProjectTabel_2 = QtWidgets.QTableView(self.runProject_6)
        self.tbRunningProjectTabel_2.setGeometry(QtCore.QRect(750, 280, 561, 411))
        self.tbRunningProjectTabel_2.setObjectName("tbRunningProjectTabel_2")
        self.cbRunningProjectActivity = QtWidgets.QComboBox(self.runProject_6)
        self.cbRunningProjectActivity.setGeometry(QtCore.QRect(180, 204, 311, 51))
        self.cbRunningProjectActivity.setStyleSheet(
            "QComboBox {\n"
            "    border: 3px solid black; \n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    background-color: #fff; \n"
            "    selection-background-color: #4CAF50; \n"
            "    color: #000;\n"
            "    font-size: 20px;\n"
            "}\n"
            "\n"
            "QComboBox::drop-down {\n"
            "    border: none;\n"
            "    background-color: transparent;\n"
            "    subcontrol-origin: padding;\n"
            "    subcontrol-position: top right;\n"
            "    width: 20px;\n"
            "}\n"
            "\n"
            "QComboBox QAbstractItemView {\n"
            "    border: 2px solid #4CAF50; \n"
            "    border-radius: 5px; \n"
            "    background-color: #fff; \n"
            "    selection-background-color: #4CAF50;\n"
            "    color: #000; \n"
            "    font-size: 14px;\n"
            "}\n"
            "\n"
            "QComboBox:hover {\n"
            "    background-color: #f0f0f0;\n"
            "}\n"
            ""
        )
        self.cbRunningProjectActivity.setObjectName("cbRunningProjectActivity")
        self.cbRunningProjectActivity.addItem("")
        self.cbRunningProjectActivity.addItem("")
        self.cbRunningProjectActivity.addItem("")
        self.cbRunningProjectActivity.addItem("")
        self.cbRunningProjectActivity.addItem("")
        self.label_33 = QtWidgets.QLabel(self.runProject_6)
        self.label_33.setGeometry(QtCore.QRect(40, 140, 141, 41))
        self.label_33.setStyleSheet(
            "QLabel {\n" "    font-size: 22px;\n" "    font-weight: bold;\n" "}"
        )
        self.label_33.setObjectName("label_33")
        self.btRunningProjectRun_2 = QtWidgets.QPushButton(self.runProject_6)
        self.btRunningProjectRun_2.setGeometry(QtCore.QRect(630, 360, 91, 51))
        self.btRunningProjectRun_2.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.btRunningProjectRun_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunningProjectRun_2.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunningProjectRun_2.setIconSize(QtCore.QSize(50, 50))
        self.btRunningProjectRun_2.setFlat(False)
        self.btRunningProjectRun_2.setObjectName("btRunningProjectRun_2")
        self.btRunningProjectRun_3 = QtWidgets.QPushButton(self.runProject_6)
        self.btRunningProjectRun_3.setGeometry(QtCore.QRect(630, 420, 91, 51))
        self.btRunningProjectRun_3.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor)
        )
        self.btRunningProjectRun_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btRunningProjectRun_3.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 20px;\n"
            "    background: red;\n"
            "    color: white;\n"
            "    font-weight: bold;\n"
            "    font-size: 20px;\n"
            "    border: 3px solid black;\n"
            "      text-align: center;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qradialgradient(\n"
            "        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
            "        );\n"
            "    color: black;\n"
            "    border: 3px solid black;\n"
            "    }\n"
            "\n"
            "QPushButton:pressed {\n"
            "    border-style: inset;\n"
            "    background: qradialgradient(\n"
            "        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
            "        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
            "        );\n"
            "    }\n"
            "\n"
            "QPushButton::icon {\n"
            "    margin-bottom: 5px; \n"
            "}\n"
            ""
        )
        self.btRunningProjectRun_3.setIconSize(QtCore.QSize(50, 50))
        self.btRunningProjectRun_3.setFlat(False)
        self.btRunningProjectRun_3.setObjectName("btRunningProjectRun_3")
        self.cbRunningProjectNama = QtWidgets.QComboBox(self.runProject_6)
        self.cbRunningProjectNama.setGeometry(QtCore.QRect(180, 140, 311, 51))
        self.cbRunningProjectNama.setStyleSheet(
            "QComboBox {\n"
            "    border: 3px solid black; \n"
            "    border-radius: 10px;\n"
            "    padding: 5px;\n"
            "    background-color: #fff; \n"
            "    selection-background-color: #4CAF50; \n"
            "    color: #000;\n"
            "    font-size: 20px;\n"
            "}\n"
            "\n"
            "QComboBox::drop-down {\n"
            "    border: none;\n"
            "    background-color: transparent;\n"
            "    subcontrol-origin: padding;\n"
            "    subcontrol-position: top right;\n"
            "    width: 20px;\n"
            "}\n"
            "\n"
            "QComboBox QAbstractItemView {\n"
            "    border: 2px solid #4CAF50; \n"
            "    border-radius: 5px; \n"
            "    background-color: #fff; \n"
            "    selection-background-color: #4CAF50;\n"
            "    color: #000; \n"
            "    font-size: 14px;\n"
            "}\n"
            "\n"
            "QComboBox:hover {\n"
            "    background-color: #f0f0f0;\n"
            "}\n"
            ""
        )
        self.cbRunningProjectNama.setObjectName("cbRunningProjectNama")
        self.cbRunningProjectNama.addItem("")
        self.cbRunningProjectNama.addItem("")
        self.cbRunningProjectNama.addItem("")
        self.cbRunningProjectNama.addItem("")
        self.cbRunningProjectNama.addItem("")
        self.stackedWidget.addWidget(self.runProject_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btToGetStarted.setText(_translate("MainWindow", "Create Project"))
        self.btRunning.setText(_translate("MainWindow", "Open Project"))
        self.label.setText(_translate("MainWindow", "Welcome to RPA Integration"))
        self.btLogout.setText(_translate("MainWindow", "Logout"))
        self.btRestart.setText(_translate("MainWindow", "Restart"))
        self.btRunning_2.setText(_translate("MainWindow", "Run Program"))
        self.label_50.setText(_translate("MainWindow", "Create Project"))
        self.btCreateProjectKembali.setText(_translate("MainWindow", "Back"))
        self.lbCreateProjectKode.setText(_translate("MainWindow", "$getCode"))
        self.label_51.setText(_translate("MainWindow", "Project name"))
        self.label_52.setText(_translate("MainWindow", "Search Data"))
        self.lbGetData_11.setText(_translate("MainWindow", "Project List Item"))
        self.btCreateProjectSimpan.setText(_translate("MainWindow", "Save"))
        self.label_53.setText(_translate("MainWindow", "Description"))
        self.label_5.setText(_translate("MainWindow", "X"))
        self.label_4.setText(_translate("MainWindow", "COORDINATS SETUP"))
        self.btIntegrationSimpan.setText(_translate("MainWindow", "Save"))
        self.btIntegrationKembali.setText(_translate("MainWindow", "Back"))
        self.btBack_2.setText(_translate("MainWindow", "Back"))
        self.btintegrationSetData.setText(_translate("MainWindow", "Set Data"))
        self.label_7.setText(_translate("MainWindow", "Insert Description"))
        self.txtIntegrationKet.setPlaceholderText(
            _translate("MainWindow", "Please insert description**")
        )
        self.btIntegrationReset.setText(_translate("MainWindow", "Reset"))
        self.btIntegrationEdit.setText(_translate("MainWindow", "Edit"))
        self.txtIntegrationDelay.setPlaceholderText(
            _translate("MainWindow", "Insert delay if you needed")
        )
        self.label_55.setText(_translate("MainWindow", "Insert Delay Process"))
        self.btIntegrationHapus.setText(_translate("MainWindow", "Delete"))
        self.label_10.setText(_translate("MainWindow", "Search Data"))
        self.btIntegrationCari.setText(_translate("MainWindow", "Search"))
        self.label_11.setText(_translate("MainWindow", "Coordinats Table"))
        self.label_14.setText(_translate("MainWindow", "Coordinat Code"))
        self.label_6.setText(_translate("MainWindow", "Y"))
        self.label_8.setText(_translate("MainWindow", "Z"))
        self.label_9.setText(_translate("MainWindow", "K"))
        self.label_29.setText(_translate("MainWindow", "Save Activity"))
        self.btSaveActivityKembali.setText(_translate("MainWindow", "Back"))
        self.label_31.setText(_translate("MainWindow", "Activity Name"))
        self.lbGetData_5.setText(_translate("MainWindow", "Activity List Item"))
        self.btSaveActivitySimpan.setText(_translate("MainWindow", "Save"))
        self.label_54.setText(_translate("MainWindow", "Description"))
        self.btSaveActivityCari.setText(_translate("MainWindow", "Search"))
        self.label_30.setText(_translate("MainWindow", "Search Data"))
        self.label_32.setText(_translate("MainWindow", "Activity Code"))
        self.txtOpenProjectGetData.setText(_translate("MainWindow", "$getData"))
        self.pushButton_3.setText(_translate("MainWindow", "Back"))
        self.label_12.setText(_translate("MainWindow", "Open Project"))
        self.btOpenProjectKembali.setText(_translate("MainWindow", "Back"))
        self.btOpenProjectBuka.setText(_translate("MainWindow", "Open"))
        self.btOpenProjectCari.setText(_translate("MainWindow", "Search"))
        self.label_13.setText(_translate("MainWindow", "Search Data"))
        self.txtRunningProjectGetData.setText(_translate("MainWindow", "$getData"))
        self.btRunningProjectCari.setText(_translate("MainWindow", "Search"))
        self.label_27.setText(_translate("MainWindow", "Choose data"))
        self.label_28.setText(_translate("MainWindow", "Running Project"))
        self.btRunningProjectKembali.setText(_translate("MainWindow", "Back"))
        self.btRunningProjectRun.setText(_translate("MainWindow", "Run"))
        self.cbRunningProjectActivity.setItemText(
            0, _translate("MainWindow", "Choose your activity")
        )
        self.cbRunningProjectActivity.setItemText(1, _translate("MainWindow", "1"))
        self.cbRunningProjectActivity.setItemText(2, _translate("MainWindow", "2"))
        self.cbRunningProjectActivity.setItemText(3, _translate("MainWindow", "3"))
        self.cbRunningProjectActivity.setItemText(4, _translate("MainWindow", "4"))
        self.label_33.setText(_translate("MainWindow", "Project"))
        self.btRunningProjectRun_2.setText(_translate("MainWindow", ">>>"))
        self.btRunningProjectRun_3.setText(_translate("MainWindow", "<<<"))
        self.cbRunningProjectNama.setItemText(
            0, _translate("MainWindow", "Choose your project name")
        )
        self.cbRunningProjectNama.setItemText(1, _translate("MainWindow", "1"))
        self.cbRunningProjectNama.setItemText(2, _translate("MainWindow", "2"))
        self.cbRunningProjectNama.setItemText(3, _translate("MainWindow", "3"))
        self.cbRunningProjectNama.setItemText(4, _translate("MainWindow", "4"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
